server {
  listen 8080;
  server_name claims.suncorp.com.au;

  root /usr/share/nginx/html;
  index index.html;

  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-Content-Type-Options "nosniff";

  location /claims-api/ {
    proxy_pass https://api.suncorp.com.au/claims/;
    proxy_set_header X-Channel CLAIMS-PORTAL;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
